// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0EHsBggd1ZmNEDVWmAd5q0hqrWsQiPnE',
    appId: '1:400512326050:web:a59b5d3e4fbb17013dbafb',
    messagingSenderId: '400512326050',
    projectId: 'chat-app-4bf14',
    authDomain: 'chat-app-4bf14.firebaseapp.com',
    storageBucket: 'chat-app-4bf14.firebasestorage.app',
    measurementId: 'G-54N8RS4N14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3yoSjwnHm1-G9dsswzBBxntw9DXCQA-E',
    appId: '1:400512326050:android:c416864148d995da3dbafb',
    messagingSenderId: '400512326050',
    projectId: 'chat-app-4bf14',
    storageBucket: 'chat-app-4bf14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkhU0rL_NZV9_gnASjzIz8_d0iTouBQxY',
    appId: '1:400512326050:ios:07617e2a3ff3cdb63dbafb',
    messagingSenderId: '400512326050',
    projectId: 'chat-app-4bf14',
    storageBucket: 'chat-app-4bf14.firebasestorage.app',
    iosBundleId: 'com.example.collabDoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkhU0rL_NZV9_gnASjzIz8_d0iTouBQxY',
    appId: '1:400512326050:ios:07617e2a3ff3cdb63dbafb',
    messagingSenderId: '400512326050',
    projectId: 'chat-app-4bf14',
    storageBucket: 'chat-app-4bf14.firebasestorage.app',
    iosBundleId: 'com.example.collabDoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLoDf9ppmnc-tbHZQ4ZIG8aGmkKPne0_M',
    appId: '1:400512326050:web:c7b336a9085065f73dbafb',
    messagingSenderId: '400512326050',
    projectId: 'chat-app-4bf14',
    authDomain: 'chat-app-4bf14.firebaseapp.com',
    storageBucket: 'chat-app-4bf14.firebasestorage.app',
    measurementId: 'G-7BGQG2KWP0',
  );
}
